### PR TITLE
Feature/travis ci

### PR DESCRIPTION
**Pull request by heathsnow**
- [ ] @sneal

* Travis-Ci build added
* TeamCity build added
* Rakefile added
* Spec tests added
* Kitchen updated

Addresses Issue https://github.com/daptiv/seven_zip/issues/8

### CODE REVIEW

**Comment by sneal** [comment]
@heathsnow version.txt file shouldn't be committed.

**Comment by heathsnow** [comment]
@sneal

* removed verson.txt (`git rm version.txt`)

**Comment by sneal** [comment]
LGTM. I'm going to bump the major version to v2.0.0 and release to SuperMarket sometime in the near future. There's quite a few changes in the master branch, some of which are breaking changes.

**Comment by heathsnow** [comment]
Sounds good.  I'll leave this open and you can merge when you do the SuperMarket release.  Feel free to tag w/2.0.0 as well :)

**Pull request merged**
